# Generated by Django 5.2 on 2025-12-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='is_myp',
            new_name='is_mvp',
        ),
    ]
